# Generated by Django 6.0.2 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technical'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
